package com.jxguo.drools;
import com.jxguo.drools.bean.Person;

global org.springframework.context.ApplicationContext ApplicationContext;

rule "2"
	when
        $p : Person(age > 30);
    then
		System.out.println("hello, young xu2!");
end

rule "3"
	when
        $p : Person(age > 10);
    then
		System.out.println("hello, zq!");
end


rule "4"
	when
        $p : Person(age > 10);
    then
		System.out.println("hello, guojianxin!");
end